name: healman_mental_awareness
description: "Healman, solusi Android inovatif untuk meningkatkan kesadaran kesehatan mental remaja di Indonesia. Aplikasi ini hadir sebagai respons terhadap kurangnya akses dan pemahaman terhadap kesehatan mental. Dengan informasi valid, panduan self-help, dan alat pengenalan masalah, kami berharap aplikasi ini memberikan kontribusi positif dalam mengatasi tantangan kesehatan mental remaja, didukung oleh pendekatan teknologi yang inovatif."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.0.0
  audioplayers: ^5.2.1

  # Firebase
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  cloud_firestore: ^4.14.0
  firebase_analytics: ^10.8.0

  http: ^1.2.0
  provider: ^6.1.1
  google_sign_in: ^6.2.1
  cupertino_icons: ^1.0.2
  connectivity_plus: ^5.0.2
  shared_preferences: ^2.2.2
  salomon_bottom_bar: ^3.3.2
  rounded_loading_button: ^2.1.0
  font_awesome_icon_class: ^0.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  
  flutter_launcher_icons: ^0.13.1
  flutter_lints: ^3.0.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"

flutter:
  uses-material-design: true
  assets:
    - assets/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf