// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC10djVIBhVOmoiO1GdlMUnnaHlKvihV5c',
    appId: '1:138087496034:web:829a193f28dd5e42c1943b',
    messagingSenderId: '138087496034',
    projectId: 'mentalawareness-healman',
    authDomain: 'mentalawareness-healman.firebaseapp.com',
    storageBucket: 'mentalawareness-healman.appspot.com',
    measurementId: 'G-ZR823X3T51',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyArYONrcp9dfvO_RatPvx_v88W01ocBPoY',
    appId: '1:138087496034:android:1575ed63dfb6a2d9c1943b',
    messagingSenderId: '138087496034',
    projectId: 'mentalawareness-healman',
    storageBucket: 'mentalawareness-healman.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_jDcPI4IKuUamZvTbIqpc1WnQkHJ22Nk',
    appId: '1:138087496034:ios:57c950151673a9ccc1943b',
    messagingSenderId: '138087496034',
    projectId: 'mentalawareness-healman',
    storageBucket: 'mentalawareness-healman.appspot.com',
    androidClientId: '138087496034-pjdqp5pkai64pbrc03t7n6tfo7r5fqm3.apps.googleusercontent.com',
    iosClientId: '138087496034-fbgf4ah7jd3upd29sdkmmc2ooo02l4ko.apps.googleusercontent.com',
    iosBundleId: 'com.example.healmanMentalAwareness',
  );
}
